// <auto-generated />
namespace PassionProject_N01457602.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dataadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dataadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202102200143186_dataadded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
