// <auto-generated />
namespace PassionProject_N01457602.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class employee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(employee));
        
        string IMigrationMetadata.Id
        {
            get { return "202102151915243_employee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
